"""Added description field to Subject model

Revision ID: 8806c5f96eb3
Revises: bd63145ebf7f
Create Date: 2025-03-29 21:47:06.057533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8806c5f96eb3'
down_revision = 'bd63145ebf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
